### ISSUE TITLE
LOD2表示時のエラー

### ISSUE THREAD

**Issue by sai-sen-tan** [AcculusSasao/plateaupy#1]
以下のLOD1表示に関してはエラーなく表示されましたが、
python appviewer.py -paths CityGML2020/plateau-14100-yokohama-city-2020 -loc 53391541
LOD2を表示させようと以下のコマンドを実行したところエラーが発生しました。
python appviewer.py -paths CityGML2020/plateau-14100-yokohama-city-2020 -loc 53391541 -k 0 -lod2texture

エラーメッセージは以下の通りです。

C:\Users\yasuda\plateau\plateaupy\plateaupy\plbldg.py:96: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  par.targets[uri] = np.array([str2floats(v).reshape((-1,2)) for v in at.xpath('app:TexCoordList/app:textureCoordinates', namespaces=nsmap)])
Traceback (most recent call last):
  File "appviewer.py", line 51, in <module>
    pl.loadFiles( bLoadCache=args.cache, cachedir=args.cachepath, kind=args.kind, location=args.location, options=options )
  File "C:\Users\yasuda\plateau\plateaupy\plateaupy\plparser.py", line 154, in loadFiles
    obj = plbldg(f, options=options)
  File "C:\Users\yasuda\plateau\plateaupy\plateaupy\plbldg.py", line 82, in __init__
    self.loadFile(filename, options=options)
  File "C:\Users\yasuda\plateau\plateaupy\plateaupy\plbldg.py", line 256, in loadFile
    mesh.triangle_uvs.extend( [ b.partex.targets[key][0,x] for x in triangles.reshape((-1)) ] )
  File "C:\Users\yasuda\plateau\plateaupy\plateaupy\plbldg.py", line 256, in <listcomp>
    mesh.triangle_uvs.extend( [ b.partex.targets[key][0,x] for x in triangles.reshape((-1)) ] )
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

エラー回避のために何が必要かについてアドバイス頂けましたら幸いです。
宜しくお願い致します。

**Comment by AcculusSasao** [comment]
ご連絡ありがとうございます。こちらでも同様でしたので修正しました。
原因は該当箇所 53391541_bldg_6697_op.gml の #ID_a8a22c1c-b866-4166-ab4b-87cc23bd181a が、4つのtextureCoordinatesを持ちますが他と違って各textureCoordinatesの数が異なることでした。

これで表示はできますが、テクスチャの法線向きなどが正しくないようです。
実はLOD2テクスチャ表示 -lod2texture は、おまけ程度で、あまり力を入れていません。
またやる気になればデバッグしてみます。

**Comment by sai-sen-tan** [comment]
ありがとうございました。
